repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
  - repo: local
    hooks:
      - id: check-build
        name: check-build
        language: system
        entry: ./scripts/check_build.py
