include: package:analysis_options/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
  exclude:
    - lib/pb

linter:
  rules:
    prefer_relative_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    diagnostic_describe_all_properties: false
