name: toc_machine_trading_ipad
description: App for ToC Machine Trading

publish_to: "none"

version: 1.0.0+10000
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  wakelock: ^0.6.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/google_fonts/
