name: toc_machine_trading_ipad
description: App for ToC Machine Trading
publish_to: "none"
version: 1.0.0+10000
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  date_format: ^2.0.7
  elegant_notification: ^1.6.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
  intl: ^0.17.0
  numberpicker: ^2.1.1
  percent_indicator: ^4.2.2
  protobuf: ^2.1.0
  syncfusion_flutter_charts: ^20.3.59
  wakelock: ^0.6.2
  web_socket_channel: ^2.2.0

dev_dependencies:
  analysis_options: any
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/google_fonts/
